//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasteleriaMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.Encargos = new HashSet<Encargos>();
            this.Ventas = new HashSet<Ventas>();
        }
    
        public int idCliente { get; set; }


        [Required(ErrorMessage = "Campo obligatorio")]
        public string nombres { get; set; }


        [Required(ErrorMessage = "Campo obligatorio")]
        [RegularExpression("[A-Za-z]*", ErrorMessage = "Solo se permite letras")]
        public string apellidoP { get; set; }


        [RegularExpression("[A-Za-z]*", ErrorMessage = "Solo se permite letras")]
        public string apellidoM { get; set; }


        [Required(ErrorMessage = "Selecciona un Estado")]
        public int idEstado { get; set; }

        [Required(ErrorMessage = "Selecciona un Municipio")]
        public int idMunicipios { get; set; }

        [Required(ErrorMessage = "Campo obligatorio")]
        public string calle { get; set; }

        [Required(ErrorMessage = "Campo obligatorio")]
        public string colonia { get; set; }


        [RegularExpression("[0-9]*", ErrorMessage = "Solo permite números")]
        [StringLength(10, ErrorMessage = "Solo diez caracteres")]
        [MinLength(10, ErrorMessage = "Deben de ser 10 Caracteres")]
        [Required(ErrorMessage = "Campo obligatorio")]
        public string celular { get; set; }


        [RegularExpression("[0-9]*", ErrorMessage = "Solo permite números")]
        [StringLength(10, ErrorMessage = "Solo diez caracteres")]
        [MinLength(10, ErrorMessage = "Deben de ser 10 Caracteres")]
        public string telefono { get; set; }


        [EmailAddress]
        [Required(ErrorMessage = "Campo obligatorio")]
        public string correo { get; set; }
    
        public virtual estados estados { get; set; }
        public virtual municipios municipios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Encargos> Encargos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas> Ventas { get; set; }
    }
}
