//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasteleriaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encargos
    {
        public int idEncargo { get; set; }
        public int idCliente { get; set; }
        public Nullable<double> anticipo { get; set; }
        public Nullable<System.DateTime> fechaEncargo { get; set; }
        public Nullable<System.DateTime> fechaEntrega { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual DetalleEncargos DetalleEncargos { get; set; }
    }
}
