//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasteleriaMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Ventas = new HashSet<Ventas>();
            this.Cargos = new HashSet<Cargos>();
        }
    
        public int idUsuario { get; set; }


        [Required(ErrorMessage = "Campo obligatorio")]
        public string nombres { get; set; }


        [Required(ErrorMessage = "Campo obligatorio")]
        public string apellidoP { get; set; }
        public string apellidoM { get; set; }


        [EmailAddress]
        [Required(ErrorMessage = "Campo obligatorio")]
        public string correo { get; set; }


        [StringLength(12, ErrorMessage = "Solo permite un maximo de 12 Caracteres")]
        [MinLength(8, ErrorMessage = "Deben de ser 8 caracteres minimo")]
        [Required(ErrorMessage = "Contraseña obligatoria")]
        public string pass { get; set; }

        [Required(ErrorMessage = "Obligatorio seleccionar un rol")]
        public int idTipo { get; set; }
    
        public virtual TipoUsuario TipoUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ventas> Ventas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cargos> Cargos { get; set; }
    }
}
